server:
# Set up server port
  port: 6010

spring:
  application:
    name: sugarmark
  profiles:
    active: dev
# Deploy the mysql8.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sugarmark?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: mysql404
    type: com.alibaba.druid.pool.DruidDataSource
# Deploy nacos
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:6006
      eager: true
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        timeout: 5000
      discovery:
        enabled: true
# Deploy mybatis
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    auto-mapping-behavior: full
logging:
  level:
    org:
      freefly:
        dodaily:
          sugarmark:
            mapper: debug
