server:
# Set up server port
  port: 16005

spring:
  application:
    name: gateway
  profiles:
    active: dev

# Deploy nacos
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        timeout: 5000
        enabled: true
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: sugarmark
          uri: lb://sugarmark
          predicates:
            - Path=/sugarmark/**
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/user/**
      default-filters:
        - AddRequestHeader=origin, DODAILY_GATEWAY
feign:
  httpclient:
    enabled: true
    connection-timeout: 5000

