package org.freefly.dodaily.common;

import org.freefly.dodaily.dao.PaidInfoIF;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * tool for all, singleton, sync*
 * @usage import it from spring map, invoke the functions
 *
 * entity needs id info to store itself,
 * the info is generated by the service which bases on the number in the databases.
 *
 * @author freefly365
 * @date 2523-07-29
 *
 * */
@Service
public class SyncIdInfo {

    @Autowired
    private PaidInfoIF piif;

    public int syncPaidInfo(){
        return piif.doCount(null);
    }
}
