server:
  port: 16007

spring:
  rabbitmq:
    host: 127.0.0.1
    username: root
    password: root1234
    virtual-host: /
    port: 5672
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 3
          max-attempts: 3
          stateless: true
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: utf-8
    username: 111
    password: 222
    port: 25
  thymeleaf:
    mode: HTML


